sonar.projectKey=JMU-TIMIMA01-BE
sonar.qualitygate.wait=true
sonar.sources=src
sonar.exclusions=**/*_test.py,**/tests/**,**/.venv/**,**/node_modules/**
sonar.python.coverage.reportPaths=coverage.xml

